language: android
sudo: false
jdk: oraclejdk8

addons:
  apt:
    packages:
      - lynx

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/